dico_mapping = \
{
	'lum':{
		1 : "Plein jour",
		2 : "Crépuscule ou aube",
		3 : "Nuit sans éclairage public",
		4 : "Nuit avec éclairage public non allumé ",
		5 : "Nuit avec éclairage public allumé",
	},
	'agg':{
	1 : "Hors agglomération",
	2 : "En agglomération",
	},
	'int':{
	1 : "Hors intersection",
	2 : "Intersection en X",
	3 : "Intersection en T",
	4 : "Intersection en Y",
	5 : "Intersection à plus de 4 branches",
	6 : "Giratoire",
	7 : "Place",
	8 : "Passage à niveau ",
	9 : "Autre intersection",
	},
	'atm':{
	1 : "Normale",
	2 : "Pluie légère",
	3 : "Pluie forte",
	4 : "Neige - grêle",
	5 : "Brouillard - fumée ",
	6 : "Vent fort - tempête ",
	7 : "Temps éblouissant ",
	8 : "Temps couvert",
	9 : "Autre",
	},
	'col':{
	1 : "Deux véhicules - frontale",
	2 : "Deux véhicules – par l’arrière",
	3 : "Deux véhicules – par le coté",
	4 : "Trois véhicules et plus – en chaîne",
	5 : "Trois véhicules et plus - collisions multiples ",
	6 : "Autre collision",
	7 : "Sans collision",
	},
	'gps':{
	"M" : "Métropole",
	"A" : "Antilles (Martinique ou Guadeloupe) ",
	"G" : "Guyane",
	"R" : "Réunion",
	"Y" : "Mayotte",
	},
	'circ':{
	1 : "A sens unique",
	2 : "Bidirectionnelle",
	3 : "A chaussées séparées",
	4 : "Avec voies d’affectation variable",
	},
	'vosp':{
	1 : "Piste cyclable",
	2 : "Banque cyclable ",
	3 : "Voie réservée",
	},
	'prof':{
	1 : "Plat",
	2 : "Pente",
	3 : "Sommet de côte",
	4 : "Bas de côte",
	},
	'plan':{
	1 : "Partie rectiligne",
	2 : "En courbe à gauche",
	3 : "En courbe à droite",
	4 : "En « S »",

	},
	'surf':{
	1 : "normale",
	2 : "mouillée",
	3 : "flaques",
	4 : "inondée",
	5 : "enneigée",
	6 : "boue",
	7 : "verglacée",
	8 : "corps gras - huile ",
	9 : "autre",
	},
	'infra':{
	1 : "Souterrain - tunnel",
	2 : "Pont - autopont",
	3 : "Bretelle d’échangeur ou de raccordement",
	4 : "Voie ferrée",
	5 : "Carrefour aménagé",
	6 : "Zone piétonne",
	7 : "Zone de péage",
	},
	'situ':{
	1 : "Sur chaussée",
	2 : "Sur bande d’arrêt d’urgence ",
	3 : "Sur accotement",
	4 : "Sur trottoir",
	5 : "Sur piste cyclable",
	},
	'senc':{
	1 : "PK ou PR ou numéro d’adresse postale croissant",
	2 : "PK ou PR ou numéro d’adresse postale décroissant",
	},
	'catv':{
	 1 : "Bicyclette",
	 2 : "Cyclomoteur <50cm3",
	 3 : "Voiturette (Quadricycle à moteur carrossé) (anciennement voiturette ou tricycle à moteur)",
	 4 : "Référence plus utilisée depuis 2006 :scooter immatriculé)",
	 5 : "Référence plus utilisée depuis 2006 :motocyclette)",
	 6 : "Référence plus utilisée depuis 2006 :side-car)",
	 7 : "VL seul",
	 8 : "Catégorie plus utilisée (VL + caravane)",
	 9 : "Catégorie plus utilisée (VL + remorque)",
	10 : "VU seul 1,5T <= PTAC <= 3,5T avec ou sans remorque (anciennement VU seul 1,5T <= PTAC <= 3,5T)",
	11 : "Référence plus utilisée depuis 2006 (caravane)",
	12 : "Référence plus utilisée depuis 2006 (remorque)",
	13 : "PL seul 3,5T <PTCA <= 7,5T",
	14 : "PL seul > 7,5T",
	15 : "PL > 3,5T + remorque",
	16 : "Tracteur routier seul",
	17 : "Tracteur routier + semi-remorque",
	18 : "Référence plus utilisée depuis 2006 (transport en commun)",
	19 : "Référence plus utilisée depuis 2006 (tramway)",
	20 : "Engin spécial",
	21 : "Tracteur agricole",
	30 : "Scooter < 50 cm3",
	31 : "Motocyclette > 50 cm3 a <= 125 cm3",
	32 : "Scooter >50cm3 et <=125cm3",
	33 : "Motocyclette > 125 cm3",
	34 : "Scooter > 125 :cm3",
	35 : "Quad léger <= 50 cm3 :Quadricycle à moteur non carrossé)",
	36 : "Quad lourd > 50 cm3 :Quadricycle à moteur non carrossé)",
	37 : "Autobus",
	38 : "Autocar",
	39 : "Train",
	40 : "Tramway",
	99 : "Autre véhicule",
	},

	'obs':{
	1 : "Véhicule en stationnement",
	2 : "Arbre",
	3 : "Glissière métallique",
	4 : "Glissière béton",
	5 : "Autre glissière",
	6 : "Bâtiment, mur, pile de pont",
	7 : "Support de signalisation verticale ou poste d’appel d’urgence ",
	8 : "Poteau",
	9 : "Mobilier urbain",
	10 : "Parapet",
	11 : "Ilot, refuge, borne haute",
	12 : "Bordure de trottoir",
	13 : "Fossé, talus, paroi rocheuse",
	14 : "Autre obstacle fixe sur chaussée",
	15 : "Autre obstacle fixe sur trottoir ou accotement",
	16 : "Sortie de chaussée sans obstacle",
	},

	'obsm':{
	1 : "Piéton",
	2 : "Véhicule",
	4 : "Véhicule sur rail",
	5 : "Animal domestique ",
	6 : "Animal sauvage",
	9 : "Autre",
	},

	'choc':{
	1 : "Avant",
	2 : "Avant droit",
	3 : "Avant gauche",
	4 : "Arrière",
	5 : "Arrière droit",
	6 : "Arrière gauche",
	7 : "Côté droit",
	8 : "Côté gauche",
	9 : "Chocs multiples (tonneaux)",
	},

	'manv':{
	1 : "Sans changement de direction",
	2 : "Même sens, même file",
	3 : "Entre 2 files",
	4 : "En marche arrière",
	5 : "A contresens",
	6 : "En franchissant le terre-plein central",
	7 : "Dans le couloir bus, dans le même sens ",
	8 : "Dans le couloir bus, dans le sens inverse ",
	9 : "En s’insérant",
	10 : "En faisant demi-tour sur la chaussée",
	11 : "A gauche",
	12 : "A droite",
	13 : "A gauche",
	14 : "A droite",
	15 : "A gauche",
	16 : "A droite",
	17 : "A gauche",
	18 : "A droite",
	19 : "Traversant la chaussée",
	20 : "Manœuvre de stationnement",
	21 : "Manœuvre d’évitement",
	22 : "Ouverture de porte",
	23 : "Arrêté (hors stationnement)",
	24 : "En stationnement (avec occupants)",


	},
	'catu':{
	1 : "Conducteur",
	2 : "Passager",
	3 : "Piéton",
	4 : "Piéton en roller ou en trottinette",
	},
	'grav':{
	1 : "Indemne",
	2 : "Tué",
	3 : "Blessé hospitalisé ",
	4 : "Blessé léger",
	},
	'sexe':{
	1 : "Masculin",
	2 : "Féminin",
	},
	'trajet':{
	1 : "Domicile – travail",
	2 : "Domicile – école",
	3 : "Courses – achats",
	4 : "Utilisation professionnelle ",
	5 : "Promenade – loisirs",
	9 : "Autre",



	},
	'locp':{
	1 : "A + 50 : du passage piéton ",
	2 : "A – 50 : du passage piéton",
	3 : "Sans signalisation lumineuse ",
	4 : "Avec signalisation lumineuse",
	5 : "Sur trottoir",
	6 : "Sur accotement",
	7 : "Sur refuge ou BAU ",
	8 : "Sur contre allée",

	},
	'actp':{
	0 : "non renseigné ou sans objet ",
	1 : "Sens véhicule heurtant",
	2 : "Sens inverse du véhicule Divers",
	3 : "Traversant",
	4 : "Masqué",
	5 : "Jouant – courant ",
	6 : "Avec animal",
	9 : "Autre",

	},
	'etatp':{
	1 : "Seul",
	2 : "Accompagné",
	3 : "En groupe"
	}
}