# Generated by Django 3.0.1 on 2020-01-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRIM', models.FloatField()),
                ('ZN', models.FloatField()),
                ('INDUS', models.FloatField()),
                ('CHAS', models.FloatField()),
                ('NOX', models.FloatField()),
                ('RM', models.FloatField()),
                ('AGE', models.FloatField()),
                ('DIS', models.FloatField()),
                ('RAD', models.FloatField()),
                ('TAX', models.FloatField()),
                ('PTRATIO', models.FloatField()),
                ('B', models.FloatField()),
                ('LSTAT', models.FloatField()),
                ('MEDV', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
