# Generated by Django 3.0.1 on 2020-01-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicteur_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='CRIM',
            field=models.FloatField(verbose_name='taux de criminalité'),
        ),
    ]
